import Head from 'next/head'
import Layout from '../public/src/components/layout'
import Posts from '../public/src/components/home/posts'

function Home() {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Posts />
    </Layout>
  )
}

export default Home